### ISSUE TITLE
Dataset license?

### ISSUE THREAD

**Issue by albertvillanova** [modestyachts/squadshifts-website#1]
Under which license is released your dataset?

Thank you.

**Comment by millerjohnp** [comment]
Hi, thanks for your patience, the dataset is released under CC-BY-4.0. Ill update the website and page accordingly to reflect that shortly.

**Comment by albertvillanova** [comment]
Thanks @millerjohnp, we have updated the license information in the Hugging Face dataset card: https://huggingface.co/datasets/squadshifts

**Comment by ludwigschmidt** [comment]
Thank you!
